### ISSUE TITLE
Scrollbar offset wrong in certain cases

### ISSUE THREAD

**Issue by renevanderlende** [rogerluiz/Miniscroll-JS#23]
Hi Roger,

Great little scroll script you created! I tried quite a few and yours came out best.

Found a little bug:

I Use the below CSS styles in almost every webpage I create, but when the "max-width" of the <body> 
is less than its "width", the scrollbar is pushed too far inside the scrolling element. I think it should be 
using the wider of the 2 values (in the case of "margin: 0 auto" that is).  

html, body { height:100%; width: 100%; margin: 0; padding: 0; border: 0; font-family: sans-serif }
/* => "margin auto" will center <body> (or custom element) onscreen when max-width < 100%  */
body { max-width: 80%; max-height: 100%; margin: 0 auto }
    * { overflow: hidden; } /* Clip all overflows, no scrolling */

Cheers,
Rene

**Comment by rogerluiz** [comment]
I will do the tests and see how best to resolve this problem as soon as possible
