### ISSUE TITLE
Variable zIndex position

### ISSUE THREAD

**Issue by renevanderlende** [rogerluiz/Miniscroll-JS#24]
Hi

At the moment "zIndex" is fixed to 999, wouldn't it make more sense to inherit the parent's zIndex and add 1 ?? This way you are more certain the scrollbar shows with high zIndex number.
Alternatively you could make it modifiable.

Cheers

**Comment by rogerluiz** [comment]
it makes sense that I am making some changes in enteira class more so than possible will this update

**Comment by rogerluiz** [comment]
i think, this is resolved
