### ISSUE TITLE
Error in the script if there are some SVG tags in the document

### ISSUE THREAD

**Issue by fabiocaires** [rogerluiz/Miniscroll-JS#27]
The getElement method checks all tag's class names in the document and returns an error "Uncaught TypeError: tags[i].className.match is not a function" when try to read the class name of a svg tag.

I could fix it by adding a toString() method before match(), inside the if statement.

if (tags[i].className && tags[i].className.**toString()**.match(new RegExp("(^|\s)" + match[1] + "(\s|$)"))){
  element = tags[i];
}

Instead of
if (tags[i].className && tags[i].className.match(new RegExp("(^|\s)" + match[1] + "(\s|$)"))){
  element = tags[i];
}

I'm not sure if it is the best way to correct this issue but it's still working properly here.

**Comment by rogerluiz** [comment]
thanks man, i will add this piece of code

**Comment by rogerluiz** [comment]
added this to the code
